Check steps in operations
savushkin-r-d/ptusa-Lua-spec pull request #2
Opened 2022-08-30 13:07 UTC by AlexandrBehunkov

2022-08-30 14:10 UTC, idzm requested changes

2022-08-30 14:10 UTC, idzm commented on main.lua
> +                    oper:to_step( j )
```suggestion
                    print( "\t"..j )
                    oper:to_step( j )
```

2022-08-31 05:45 UTC, idzm requested changes

2022-08-31 05:45 UTC, idzm commented on main.lua
> +                    oper:to_step( "\t"..j )
Предлагаю добавить также печать номера шага, чтобы было видно, где ошибка:
```suggestion
                    oper:to_step( j )
                    print( "\t"..j )
```

2022-08-31 05:51 UTC, AlexandrBehunkov commented on main.lua
> +                    oper:to_step( "\t"..j )
Готово.

2022-08-31 06:07 UTC, idzm requested changes

2022-08-31 06:07 UTC, idzm commented on main.lua
> +                local oper   = m_mngr[ i ]
Убрал лишние пробелы:
```suggestion
                local oper = m_mngr[ i ]
```

2022-08-31 06:07 UTC, idzm commented on main.lua
> +                local step = oper:active_step()
Убрал не используемую локальную переменную:
```suggestion
```

2022-08-31 06:11 UTC, idzm requested changes

2022-08-31 06:11 UTC, idzm commented on main.lua
> +                    oper:to_step( j )
Предлагаю также добавить выполнение операции после перехода к шагу:
```suggestion
                    oper:to_step( j )
                    assert.are.equal( ptusa.eval(), 0 )
```

2022-08-31 06:12 UTC, AlexandrBehunkov commented on main.lua
> +                    oper:to_step( j )
Как скажете

2022-08-31 06:19 UTC, idzm approved these changes

2022-08-31 07:25 UTC, alexandraneroda approved these changes

2022-09-01 07:21 UTC, merged